<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:sparql="http://www.w3.org/2005/sparql-results#"
	xmlns="http://www.w3.org/1999/xhtml">

	<xsl:include href="../locale/messages.xsl" />

	<xsl:variable name="title">
		PoMS RDF Server: Welcome
		
	</xsl:variable>

	<xsl:include href="template.xsl" />

	<xsl:template match="sparql:sparql">
		<xsl:variable name="info" select="/" />
		<p>Welcome to the PoMS RDF Server, which provides open RDF-oriented access to the data created by
		the <i>People of Medieval Scotland</i> project.
		More about PoMS itself outside of its RDF representation can be found <a href="http://www.poms.ac.uk">here</a>.</p>
		<h3>Navigation</h3>
        <p>All the browser-oriented pages generated by the RDF server, including this one,
        share the top banner area and the menu area on the left, and thus links found in either of them
        can always be used for navigation:</p>
		<ul>
		<li>The menu to the left focuses on links that provides a set of convenient browser-oriented ways to
		interact with this server.</li>
		<li>The links at the top right corner of the page banner provide associated information about PoMS and
		the RDF server.
		<p><b>Note:</b> Among the three links showing in the top right corner is the second item, which takes you to the
		documentation pages that describe this server. We recommend that you consult these pages before trying to
		make use of it. Go to these pages from <a href="../../doc">here</a>.</p></li>
		</ul>
		<br/><br/><br/>
		<p>This application is built with components from <a href="http://rdf4j.org/">rdf4j</a>'s workbench.</p>
		<table class="simple">
			<tbody>

				<tr>
					<th>
						<xsl:value-of select="$application-name.label" />
					</th>
					<td>
						<xsl:value-of select="$workbench.label" />
					</td>
				</tr>
				<tr>
					<th>
						RDF4J Version
					</th>
					<td>
						<xsl:value-of
							select="$info//sparql:binding[@name='version']/sparql:literal" />
					</td>
				</tr>
				<tr>
					<th>
						<xsl:value-of select="$repository-size.label" />
					</th>
					<td>
						<xsl:value-of select="//sparql:binding[@name='size']" />
					</td>
				</tr>
			</tbody>
		</table>
	</xsl:template>

	<xsl:template match="sparql:literal">
		<xsl:value-of select="." />
	</xsl:template>

</xsl:stylesheet>